In [3]:
import numpy as np
#标量
s = np.array(5)
print(s.shape)

x = s + 3
print(x)

8


In [5]:
#向量
s2 = np.array([1,2,3,4])
print(s2.shape)
print(s2[1])
print(s2[1:])

(4,)
2
[2 3 4]


In [7]:
#矩阵
s3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(s3.shape)

(3, 3)


In [9]:
#张量
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])
print(t.shape)

(3, 3, 2, 1)


In [16]:
#更改形状
a = np.array([1,2,3,4])
print(a)
print(a.shape)
x = a.reshape(4,1)
print(x)
print(x.shape)
y = a.reshape(1,4)
print(y)
print(y.shape)
#创建一个切片，查看 a 的所有项目，要求 NumPy 为相关轴添加大小为 1 的新维度
x2 = a[None, :]
print(x2)
print(x2.shape)
y2 = a[:,None]
print(y2)
print(y2.shape)

[1 2 3 4]
(4,)
[[1]
 [2]
 [3]
 [4]]
(4, 1)
[[1 2 3 4]]
(1, 4)
[[1 2 3 4]]
(1, 4)
[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [20]:
#元素级运算
#python
values = [1,2,3,4,5]
for i in range(len(values)):
    values[i] += 5
print(values)
#numpy
values = [1,2,3,4,5]
values = np.array(values)
values += 5
print(values)
#支持加减乘除
values = np.multiply(values,2)#same as below
print(values)
values *= 2
print(values)

[6, 7, 8, 9, 10]
[ 6  7  8  9 10]
[12 14 16 18 20]
[24 28 32 36 40]


In [24]:
#元素级矩阵运算
a = np.array([[1,2,3],[1,2,3]])
b = np.array([[2,3,4],[2,3,4]])
print(a+b)
print(a*2)
print(np.multiply(a,3))

[[3 5 7]
 [3 5 7]]
[[2 4 6]
 [2 4 6]]
[[3 6 9]
 [3 6 9]]


In [34]:
#矩阵乘积
a = np.array([[1,2,3,4],[5,6,7,8]])
print('a.shape ',a.shape)
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print('b.shape ',b.shape)
print(b.shape[0])
print(b.shape[1])
c = np.matmul(a, b)
print(c)
print('c.shape ',c.shape)
#dot只有在2-D的时候等同于matmul
#For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors 
#(without complex conjugation). For N dimensions it is a sum product over the last axis of a and the second-to-last of b:
d = np.dot(a,b)
print(d)

a.shape  (2, 4)
b.shape  (4, 3)
4
3
[[ 70  80  90]
 [158 184 210]]
c.shape  (2, 3)
[[ 70  80  90]
 [158 184 210]]


In [30]:
#矩阵转置,是视图，不是copy,所以虽然高效，但是修改的时候要注意
a = np.array([[1,2,3,4],[4,5,6,7]])
print(a.T)

[[1 4]
 [2 5]
 [3 6]
 [4 7]]


In [38]:
# Use the numpy library
import numpy as np


def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    print(inputs)
    input_array = np.array([inputs])
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    inputs_minus_min = input_array - np.min(input_array)

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    max_num = np.max(inputs_minus_min)
    inputs_div_max = inputs_minus_min / max_num

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max
    

def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    if m1.shape[0]!= m2.shape[1] and m1.shape[1]!= m2.shape[0]:
        return False


    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    if m1.shape[1] == m2.shape[0]:
        return np.matmul(m1,m2)
    else:
        return np.matmul(m2,m1)
    
    

def find_mean(values):
    # TODO: Return the average of the values in the given Python list
    return np.mean(values)


input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

[-1, 2, 7]
Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[ 0.     0.375  1.   ]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
[[ 9 12 15]]
Mean == 2.6666666666666665
