In [20]:
import numpy as np
test = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19])
batch_size = 3
seq_len = 2
batch_len = len(test)//(batch_size*seq_len)
test = test[:batch_len*batch_size*seq_len]
print(test)
x=np.array(test,dtype=np.int)
print(x)
y=np.array([test[i+1] if i<len(test)-1 else test[0] for i in range(len(test))],dtype=np.int)
print(y)
batches_x = np.split(x,len(x)/seq_len)
batches_y = np.split(y,len(y)/seq_len)
print(batches_x)
print(batches_y)
batch_x = np.zeros((batch_size,seq_len))
batch_y = np.zeros((batch_size,seq_len))
batches = np.zeros([batch_len,2,batch_size,seq_len],dtype=np.int)
for i in range(batch_len):
    for ii in range(batch_size):
        batch_x[ii] = batches_x[ii*batch_len + i]
        batch_y[ii] = batches_y[ii*batch_len + i]
        print(batch_x)
    batches[i]=[batch_x,batch_y]
    #print(batches[i])
print(batches)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18  1]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10]), array([11, 12]), array([13, 14]), array([15, 16]), array([17, 18])]
[array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9]), array([10, 11]), array([12, 13]), array([14, 15]), array([16, 17]), array([18,  1])]
[[ 1.  2.]
 [ 0.  0.]
 [ 0.  0.]]
[[ 1.  2.]
 [ 7.  8.]
 [ 0.  0.]]
[[  1.   2.]
 [  7.   8.]
 [ 13.  14.]]
[[  3.   4.]
 [  7.   8.]
 [ 13.  14.]]
[[  3.   4.]
 [  9.  10.]
 [ 13.  14.]]
[[  3.   4.]
 [  9.  10.]
 [ 15.  16.]]
[[  5.   6.]
 [  9.  10.]
 [ 15.  16.]]
[[  5.   6.]
 [ 11.  12.]
 [ 15.  16.]]
[[  5.   6.]
 [ 11.  12.]
 [ 17.  18.]]
[[[[ 1  2]
   [ 7  8]
   [13 14]]

  [[ 2  3]
   [ 8  9]
   [14 15]]]


 [[[ 3  4]
   [ 9 10]
   [15 16]]

  [[ 4  5]
   [10 11]
   [16 17]]]


 [[[ 5  6]
   [11 12]
   [17 18]]

  [[ 6  7]
  