In [30]:
import numpy as np
a = np.array([3,2,1])
print(a.shape)
print(a)
b = np.array([2,1])
print(b.shape)
print(a[:,None])
print(a[:,None].shape)
print('a:')
print(a[:,None]*b)
print('b')
print(a*b[:,None])
print(b[:,None]*a)
#print(np.multiply(a[:,None],b))
c = np.array([[1,2,3],[1,2,3]])
d = np.array([[1,2,3],[1,2,3]])
print(c*d)
#print(np.multiply(c,d))
e = d.T
print(c*e)


(3,)
[3 2 1]
(2,)
[[3]
 [2]
 [1]]
(3, 1)
a:
[[6 3]
 [4 2]
 [2 1]]
b
[[6 4 2]
 [3 2 1]]
[[6 4 2]
 [3 2 1]]
[[1 4 9]
 [1 4 9]]


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [10]:
a = np.array([4,5,6])
b = np.array([1,2,3])
print(b)
print(np.dot(a,b))
e = b[:,None]
print(e)
print(np.dot(a,e))
c = np.array([[2,3],[1,2],[1,2]])
d = np.array([[2,3],[1,2],[1,2]]).T
print(d.shape)
print(np.dot(c,d))

[1 2 3]
32
[[1]
 [2]
 [3]]
[32]
(2, 3)
[[13  8  8]
 [ 8  5  5]
 [ 8  5  5]]


In [20]:
import numpy as np
a = np.array([[2,3]])
b = np.array([[1,2,3]])
d =  np.array([[1,2,3],[1,2,3]])
c = b.T
print(a.shape,b.shape,c.shape)
print(a*c)
print(np.dot(c,a))
print(a.T*d)
print(np.dot(a,d))

(1, 2) (1, 3) (3, 1)
[[2 3]
 [4 6]
 [6 9]]
[[2 3]
 [4 6]
 [6 9]]
[[2 4 6]
 [3 6 9]]
[[ 5 10 15]]
