### tf.argmax&tf.equal
tf.argmax(input, axis=None, name=None, dimension=None)

此函数是对矩阵按行或列计算最大值

参数
input：输入Tensor
axis：0表示按列，1表示按行
name：名称
dimension：和axis功能一样，默认axis取值优先。新加的字段
返回：Tensor  一般是行或列的最大值下标向量

tf.argmax就是按行或者列返回最大的那个下标（从0开始）



In [6]:
import tensorflow as tf  
  
t=tf.get_variable(name='t',  
                  shape=[3,4],  
                  dtype=tf.float32,  
                  initializer=tf.random_uniform_initializer(minval=-1,maxval=1))  
b=tf.argmax(input=t,axis=0)  
c=tf.argmax(input=t,dimension=1)   #此处用dimesion或用axis是一样的  
sess = tf.InteractiveSession()  
sess.run(tf.global_variables_initializer())  
print(sess.run(t))  
#[[ 0.04261756 -0.34297419 -0.87816691 -0.15430689]  
# [ 0.18663144  0.86972666 -0.06103253  0.38307118]  
# [ 0.84588599 -0.45432305 -0.39736366  0.38526249]]  
print(sess.run(b))  
#[2 1 1 2]  
print(sess.run(c))  
#[0 1 0]  

[[-0.64484978  0.794276   -0.06333113  0.10110617]
 [ 0.06428528  0.37692761 -0.87432313 -0.34467506]
 [ 0.33612418  0.14210582 -0.31081629  0.13005662]]
[2 0 0 2]
[1 1 0]


一般情况下计算accuracy:

correct_pred = tf.equal(tf.argmax(z,1), tf.argmax(y,1))
就是分别求预测值和实际labels的按列轴求最大值的那个下标，然后equal比较预测值和实际结果是否一致。

上面这行代码会给我们一组布尔值。为了确定正确预测项的比例，我们可以用tf.cast把布尔值转换成浮点数，然后取平均值。

accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))




In [12]:
import tensorflow as tf
import numpy as np
pred = np.array([[31, 23,  4, 24, 27, 34],
                [18,  3, 25,  0,  6, 35],
                [28, 14, 33, 22, 20,  8],
                [13, 30, 21, 19,  7,  9],
                [16,  1, 26, 32,  2, 29],
                [17, 12,  5, 11, 10, 15]])

y = np.array([[31, 23,  4, 23, 27, 3],
                [18,  3, 25,  0,  6, 35],
                [28, 14, 33, 22, 20,  8],
                [13, 30, 21, 19,  7,  9],
                [16,  1, 26, 32,  2, 29],
                [17, 12,  5, 11, 10, 15]])
correct = tf.equal(tf.argmax(pred,1),tf.argmax(y,1))

accuracy = tf.reduce_mean(tf.cast(correct,"float"))

sess = tf.Session()  
sess.run(tf.global_variables_initializer())  
print(sess.run(correct))  
print(sess.run(accuracy))


[False  True  True  True  True  True]
0.833333
