In [3]:
     
import tensorflow as tf  
  
features = [[1,2,3],[4,5,6]]  
n_words=6  
outputs = tf.contrib.layers.embed_sequence(features, vocab_size=n_words, embed_dim=4)  
  
with tf.Session() as sess:  
    sess.run(tf.global_variables_initializer())  
    a=sess.run(outputs)  
    print(a)  

InvalidArgumentError: indices[1,2] = 6 is not in [0, 6)
	 [[Node: EmbedSequence_2/embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@EmbedSequence_2/embeddings"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](EmbedSequence_2/embeddings/read, EmbedSequence_2/embedding_lookup/indices)]]

Caused by op 'EmbedSequence_2/embedding_lookup', defined at:
  File "C:\ProgramData\Anaconda3\envs\py3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\py3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\IPython\core\interactiveshell.py", line 2698, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\IPython\core\interactiveshell.py", line 2802, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-d276716c93dd>", line 6, in <module>
    outputs = tf.contrib.layers.embed_sequence(features, vocab_size=n_words, embed_dim=4)
  File "C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\tensorflow\contrib\layers\python\layers\encoders.py", line 142, in embed_sequence
    return embedding_ops.embedding_lookup(embeddings, ids)
  File "C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\tensorflow\python\ops\embedding_ops.py", line 122, in embedding_lookup
    return maybe_normalize(_do_gather(params[0], ids, name=name))
  File "C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\tensorflow\python\ops\embedding_ops.py", line 42, in _do_gather
    return array_ops.gather(params, ids, name=name)
  File "C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1179, in gather
    validate_indices=validate_indices, name=name)
  File "C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\ProgramData\Anaconda3\envs\py3\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): indices[1,2] = 6 is not in [0, 6)
	 [[Node: EmbedSequence_2/embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@EmbedSequence_2/embeddings"], validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](EmbedSequence_2/embeddings/read, EmbedSequence_2/embedding_lookup/indices)]]


InvalidArgumentError (see above for traceback): indices[1,2] = 6 is not in [0, 6)
这个错是因为vocab_size是从1开始编码的

In [5]:
import tensorflow as tf  
  
features = [[1,2,3],[4,5,6]]  
n_words=6  
outputs = tf.contrib.layers.embed_sequence(features, vocab_size=n_words+1, embed_dim=4)  
  
with tf.Session() as sess:  
    sess.run(tf.global_variables_initializer())  
    a=sess.run(outputs)  
    print(a)  

[[[ 0.33321697 -0.3111788  -0.06160659  0.47495061]
  [ 0.23637664  0.14130318 -0.39757413  0.41024953]
  [ 0.17674249  0.10403806 -0.10093617  0.43691033]]

 [[ 0.64746469 -0.01632857 -0.23849583  0.45489401]
  [ 0.37316281 -0.62043333 -0.65422839 -0.68017083]
  [-0.54258931  0.19497126 -0.61900514  0.11916786]]]
