### tf.strided_slice
strided_slice这个函数实际上是tf的slice函数

strided_slice(
    input_,
    begin,
    end,
    strides=None,
    begin_mask=0,
    end_mask=0,
    ellipsis_mask=0,
    new_axis_mask=0,
    shrink_axis_mask=0,
    var=None,
    name=None
)

简单来看这个函数重点在于前四个参数：

第一个是输入数据

第二个是开始切片的地方

第三个是终止切片的地方

第四个是步长

In [9]:
import tensorflow as tf
import numpy as np
inputs = np.array([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]], [[5, 5, 5], [6, 6, 6]]])
# 'input' is [[[1, 1, 1], [2, 2, 2]],
#             [[3, 3, 3], [4, 4, 4]],
#             [[5, 5, 5], [6, 6, 6]]]
re1 = tf.strided_slice(inputs, [1, 0, 0], [2, 1, 3], [1, 1, 1])
re2  = tf.strided_slice(inputs, [1, 0, 0], [2, 2, 3], [1, 1, 1])
re3 = tf.strided_slice(inputs, [1, -1, 0], [2, -3, 3], [1, -1, 1]) 
with tf.Session() as sess:
    print(sess.run(re1))
    print(sess.run(re2))
    print(sess.run(re3))


[[[3 3 3]]]
[[[3 3 3]
  [4 4 4]]]
[[[4 4 4]
  [3 3 3]]]


In [10]:
data = [1,2,3,4,5,6,7,8]
x = tf.strided_slice(data,[0],[4])
y = tf.strided_slice(data,[1],[5])
with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(y))

[1 2 3 4]
[2 3 4 5]


'input'= [[[1, 1, 1], [2, 2, 2]],
             [[3, 3, 3], [4, 4, 4]],
             [[5, 5, 5], [6, 6, 6]]]
             
来把输入变个型,可以看成3维的tensor,从外向为1,2,3维

[

     [
     
          [1,1,1]
          
          [2,2,2]
          
     ]
     
     [
         [3,3,3]
         
         [4,4,4]
     ]
     
     [
         [5,5,5]
         
         [6,6,6]
     ]
]
以tf.strided_slice(input, [0,0,0], [2,2,2], [1,2,1])调用为例,start = [0,0,0] , end = [2,2,2], stride = [1,2,1],求一个[start, end)的一个片段,注意end为开区间

第1维 start = 0 , end = 2, stride = 1, 所以取 0 , 1行，此时的输出

output1=
[

     [
     
          [1,1,1]
          
          [2,2,2]
     ]
     
     [
     
         [3,3,3]
         
         [4,4,4]
         
     ]
]
第2维时, start = 0 , end = 2 , stride = 2, 所以只能取0行,此时的输出

output2=
[
     [
     
          [1,1,1]
          
     ]
     
     [
     
         [3,3,3]
     ]
     
]

第3维的时候,start = 0, end = 2, stride = 1, 可以取0,1行,此时得到的就是最后的输出
[

     [
     
          [1,1]
     ]
     
     [
     
         [3,3]
         
     ]
     
]

整理之后最终的输出为:

[[[1,1],[3,3]]]